<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $vehicles = [
            [
                'make' => 'Mercedes-Benz', 'model' => 'S-Class S580', 'year' => 2024,
                'price' => 118900, 'mileage' => 1240, 'exterior_color' => 'Obsidian Black',
                'interior_color' => 'Macchiato Beige', 'body_type' => 'sedan',
                'transmission' => 'automatic', 'fuel_type' => 'gasoline', 'drivetrain' => 'awd',
                'engine' => '4.0L V8 Biturbo', 'horsepower' => 496, 'condition' => 'used',
                'featured' => true,
                'hero_image' => 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&q=80',
                'description' => 'Impeccably maintained flagship sedan with the pinnacle of luxury. Features MBUX infotainment, Burmester 4D surround sound, heated and ventilated massage seats, and the full driver assistance package. One owner, dealer serviced.',
                'features' => (['Burmester 4D Sound', 'Massage Seats', 'Night Vision Assist', 'Head-Up Display', 'Panoramic Sunroof', 'Air Suspension', 'Rear Entertainment']),
            ],
            [
                'make' => 'BMW', 'model' => 'M4 Competition', 'year' => 2024,
                'price' => 84900, 'mileage' => 3200, 'exterior_color' => 'Isle of Man Green',
                'interior_color' => 'Black Merino Leather', 'body_type' => 'coupe',
                'transmission' => 'automatic', 'fuel_type' => 'gasoline', 'drivetrain' => 'rwd',
                'engine' => '3.0L I6 Twin-Turbo', 'horsepower' => 503, 'condition' => 'used',
                'featured' => true,
                'hero_image' => 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&q=80',
                'description' => 'Track-capable performance coupe in stunning Isle of Man Green. M Carbon bucket seats, M Carbon ceramic brakes, and the M Driver\'s Package. Aggressive yet refined — this is driving at its finest.',
                'features' => (['M Carbon Bucket Seats', 'Carbon Ceramic Brakes', 'M Driver\'s Package', 'Harman Kardon', 'Adaptive M Suspension', 'M Carbon Exterior']),
            ],
            [
                'make' => 'Porsche', 'model' => '911 Carrera GTS', 'year' => 2024,
                'price' => 162500, 'mileage' => 890, 'exterior_color' => 'GT Silver Metallic',
                'interior_color' => 'Black/Bordeaux Red', 'body_type' => 'coupe',
                'transmission' => 'automatic', 'fuel_type' => 'gasoline', 'drivetrain' => 'rwd',
                'engine' => '3.0L Flat-6 Twin-Turbo', 'horsepower' => 473, 'condition' => 'used',
                'featured' => true,
                'hero_image' => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80',
                'description' => 'The definitive sports car. Rear-engine, rear-drive purity with the GTS treatment — more power, sport chassis, and lightweight Sport Design package. Under 1,000 miles. Essentially new.',
                'features' => (['Sport Chrono Package', 'PASM Sport Suspension', 'Sport Exhaust', 'Bose Surround', 'Sport Design Package', 'Rear Axle Steering']),
            ],
            [
                'make' => 'Range Rover', 'model' => 'Autobiography LWB', 'year' => 2024,
                'price' => 189000, 'mileage' => 4500, 'exterior_color' => 'Carpathian Grey',
                'interior_color' => 'Perlino/Ebony', 'body_type' => 'suv',
                'transmission' => 'automatic', 'fuel_type' => 'gasoline', 'drivetrain' => 'awd',
                'engine' => '4.4L V8 Twin-Turbo', 'horsepower' => 523, 'condition' => 'used',
                'featured' => true,
                'hero_image' => 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=1200&q=80',
                'description' => 'The ultimate luxury SUV. Long wheelbase Autobiography with executive rear seats, refrigerator compartment, and Meridian Signature Sound. Effortless on any terrain, commanding in any setting.',
                'features' => (['Executive Rear Seats', 'Refrigerator', 'Meridian Signature Sound', 'Pixel LED Headlights', 'Air Suspension', 'Terrain Response 2', 'Head-Up Display']),
            ],
            [
                'make' => 'Audi', 'model' => 'RS e-tron GT', 'year' => 2024,
                'price' => 147900, 'mileage' => 2100, 'exterior_color' => 'Daytona Grey',
                'interior_color' => 'Black Valcona Leather', 'body_type' => 'sedan',
                'transmission' => 'automatic', 'fuel_type' => 'electric', 'drivetrain' => 'awd',
                'engine' => 'Dual Motor Electric', 'horsepower' => 637, 'condition' => 'used',
                'featured' => true,
                'hero_image' => 'https://images.unsplash.com/photo-1614200187524-dc4b892acf16?w=1200&q=80',
                'description' => 'Electric performance without compromise. 637 horsepower, 0-60 in 3.1 seconds, and a range that makes daily driving effortless. The future of the grand tourer, available now.',
                'features' => (['637 HP Dual Motor', 'Carbon Fiber Roof', 'Matrix LED Headlights', 'Bang & Olufsen 3D', 'Air Suspension', 'Laser Light']),
            ],
            [
                'make' => 'Toyota', 'model' => 'GR Supra 3.0 Premium', 'year' => 2024,
                'price' => 58900, 'mileage' => 5800, 'exterior_color' => 'Renaissance Red',
                'interior_color' => 'Black Leather', 'body_type' => 'coupe',
                'transmission' => 'manual', 'fuel_type' => 'gasoline', 'drivetrain' => 'rwd',
                'engine' => '3.0L I6 Turbo', 'horsepower' => 382, 'condition' => 'used',
                'featured' => false,
                'hero_image' => 'https://images.unsplash.com/photo-1632245889029-e406faaa34cd?w=1200&q=80',
                'description' => 'Rare 6-speed manual Supra in the iconic Renaissance Red. The BMW-sourced inline-six delivers relentless thrust while the chassis begs for canyon roads. A modern classic.',
                'features' => (['6-Speed Manual', 'JBL Audio', 'Adaptive Suspension', 'Launch Control', 'Wireless Charging', 'Head-Up Display']),
            ],
            [
                'make' => 'Tesla', 'model' => 'Model S Plaid', 'year' => 2024,
                'price' => 89900, 'mileage' => 8200, 'exterior_color' => 'Ultra White',
                'interior_color' => 'White Interior', 'body_type' => 'sedan',
                'transmission' => 'automatic', 'fuel_type' => 'electric', 'drivetrain' => 'awd',
                'engine' => 'Tri Motor Electric', 'horsepower' => 1020, 'condition' => 'used',
                'featured' => false,
                'hero_image' => 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=1200&q=80',
                'description' => '1,020 horsepower. 0-60 in 1.99 seconds. The fastest production sedan ever made. Full Self-Driving capability, 17-inch cinematic display, and the yoke steering wheel.',
                'features' => (['1,020 HP Tri Motor', 'Full Self-Driving', '17" Cinematic Display', 'Yoke Steering', 'Glass Roof', 'HEPA Air Filtration']),
            ],
            [
                'make' => 'Ford', 'model' => 'Mustang GT Premium', 'year' => 2024,
                'price' => 47500, 'mileage' => 6100, 'exterior_color' => 'Vapor Blue',
                'interior_color' => 'Ebony Leather', 'body_type' => 'coupe',
                'transmission' => 'manual', 'fuel_type' => 'gasoline', 'drivetrain' => 'rwd',
                'engine' => '5.0L V8', 'horsepower' => 480, 'condition' => 'used',
                'featured' => false,
                'hero_image' => 'https://images.unsplash.com/photo-1584345604476-8ec5f82d661f?w=1200&q=80',
                'description' => 'American muscle, refined. The seventh-generation Mustang GT with the rev-matching 6-speed manual, active valve exhaust, and MagneRide adaptive dampers. Pure V8 soundtrack.',
                'features' => (['6-Speed Manual', 'Active Valve Exhaust', 'MagneRide Dampers', 'B&O Sound', 'Digital Cluster', 'Performance Package']),
            ],
            [
                'make' => 'Lexus', 'model' => 'LC 500', 'year' => 2023,
                'price' => 82500, 'mileage' => 11200, 'exterior_color' => 'Infrared',
                'interior_color' => 'Toasted Caramel', 'body_type' => 'coupe',
                'transmission' => 'automatic', 'fuel_type' => 'gasoline', 'drivetrain' => 'rwd',
                'engine' => '5.0L V10', 'horsepower' => 471, 'condition' => 'used',
                'featured' => false,
                'hero_image' => 'https://images.unsplash.com/photo-1621993202323-f438eec934ff?w=1200&q=80',
                'description' => 'Rolling sculpture. The LC 500 is Lexus at its most daring — a naturally aspirated V8 grand tourer with the build quality of a Swiss watch. The Infrared over Toasted Caramel combination is breathtaking.',
                'features' => (['Mark Levinson Audio', '10-Speed Direct Shift', 'Adaptive Variable Suspension', 'Limited Slip Diff', 'Alcantara Headliner', 'Carbon Fiber Roof']),
            ],
            [
                'make' => 'Chevrolet', 'model' => 'Corvette Z06', 'year' => 2024,
                'price' => 119900, 'mileage' => 1800, 'exterior_color' => 'Riptide Blue',
                'interior_color' => 'Jet Black/Sky Cool Grey', 'body_type' => 'coupe',
                'transmission' => 'automatic', 'fuel_type' => 'gasoline', 'drivetrain' => 'rwd',
                'engine' => '5.5L Flat-Plane Crank V8', 'horsepower' => 670, 'condition' => 'used',
                'featured' => true,
                'hero_image' => 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=80',
                'description' => 'The flat-plane crank V8 screams to 8,600 RPM — a sound unlike anything American. Mid-engine, track-focused, and devastatingly fast. Carbon fiber aero package and Z07 performance package.',
                'features' => (['Flat-Plane Crank V8', 'Z07 Performance Package', 'Carbon Fiber Aero', 'Magnetic Ride Control', 'Performance Data Recorder', 'Carbon Fiber Wheels']),
            ],
            [
                'make' => 'Mercedes-Benz', 'model' => 'G63 AMG', 'year' => 2024,
                'price' => 198500, 'mileage' => 3400, 'exterior_color' => 'Matte Black',
                'interior_color' => 'Red Pepper/Black', 'body_type' => 'suv',
                'transmission' => 'automatic', 'fuel_type' => 'gasoline', 'drivetrain' => 'awd',
                'engine' => '4.0L V8 Biturbo', 'horsepower' => 577, 'condition' => 'used',
                'featured' => false,
                'hero_image' => 'https://images.unsplash.com/photo-1520031441872-265e4ff70366?w=1200&q=80',
                'description' => 'The icon. 577 horsepower in a box that hasn\'t changed its silhouette in four decades. Matte Black with the red interior is the definitive spec. Three locking differentials, because why not.',
                'features' => (['AMG Performance Exhaust', 'Designo Interior', 'Three Locking Diffs', 'Burmester Sound', 'AMG Night Package', 'Adaptive Damping']),
            ],
            [
                'make' => 'Rivian', 'model' => 'R1T Adventure', 'year' => 2024,
                'price' => 73900, 'mileage' => 9500, 'exterior_color' => 'Forest Green',
                'interior_color' => 'Ocean Coast', 'body_type' => 'truck',
                'transmission' => 'automatic', 'fuel_type' => 'electric', 'drivetrain' => 'awd',
                'engine' => 'Quad Motor Electric', 'horsepower' => 835, 'condition' => 'used',
                'featured' => false,
                'hero_image' => 'https://images.unsplash.com/photo-1666919643134-d97687c1826c?w=1200&q=80',
                'description' => 'The electric truck that actually delivers. Quad-motor all-wheel drive, tank turn capability, camp kitchen option, and the most capable off-road EV on the market. Adventure isn\'t just the trim — it\'s the lifestyle.',
                'features' => (['Quad Motor AWD', 'Tank Turn', 'Camp Kitchen', 'Powered Tonneau', 'Max Pack Battery', 'Off-Road Upgrade']),
            ],
            [
                'make' => 'Jaguar', 'model' => 'F-Type R75', 'year' => 2024,
                'price' => 108000, 'mileage' => 950, 'exterior_color' => 'British Racing Green',
                'interior_color' => 'Mars Red', 'body_type' => 'convertible',
                'transmission' => 'automatic', 'fuel_type' => 'gasoline', 'drivetrain' => 'awd',
                'engine' => '5.0L Supercharged V8', 'horsepower' => 575, 'condition' => 'used',
                'featured' => false,
                'hero_image' => 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1200&q=80',
                'description' => 'The final edition F-Type. 75th anniversary special with British Racing Green over Mars Red — a color combination that makes enthusiasts weep. Under 1,000 miles. A future collector\'s piece.',
                'features' => (['75th Anniversary Edition', 'Supercharged V8', 'Switchable Active Exhaust', 'Meridian 380W', 'Performance Seats', 'Carbon Fiber Trim']),
            ],
            [
                'make' => 'BMW', 'model' => 'X7 M60i', 'year' => 2024,
                'price' => 105900, 'mileage' => 7800, 'exterior_color' => 'Tanzanite Blue',
                'interior_color' => 'Ivory White', 'body_type' => 'suv',
                'transmission' => 'automatic', 'fuel_type' => 'gasoline', 'drivetrain' => 'awd',
                'engine' => '4.4L V8 Twin-Turbo', 'horsepower' => 523, 'condition' => 'used',
                'featured' => false,
                'hero_image' => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=80',
                'description' => 'Seven-seat luxury with M performance. The twin-turbo V8 makes this family hauler embarrassingly fast. Rear-seat entertainment, Sky Lounge panoramic roof, and Bowers & Wilkins Diamond surround.',
                'features' => (['Bowers & Wilkins Diamond', 'Sky Lounge Roof', 'Rear Entertainment', 'Air Suspension', 'M Sport Differential', 'Executive Seating']),
            ],
            [
                'make' => 'Porsche', 'model' => 'Cayenne Turbo GT', 'year' => 2024,
                'price' => 195000, 'mileage' => 2900, 'exterior_color' => 'Arctic Grey',
                'interior_color' => 'Black/Neodyme', 'body_type' => 'suv',
                'transmission' => 'automatic', 'fuel_type' => 'gasoline', 'drivetrain' => 'awd',
                'engine' => '4.0L V8 Twin-Turbo', 'horsepower' => 631, 'condition' => 'used',
                'featured' => false,
                'hero_image' => 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=1200&q=80',
                'description' => 'The Nurburgring-record-holding SUV. 631 horsepower, titanium exhaust, and carbon-ceramic brakes. It defies physics — an SUV that corners like a sports car and sounds like a race car.',
                'features' => (['Titanium Exhaust', 'Carbon Ceramic Brakes', 'PDCC Sport', 'Lightweight Sport Package', 'Rear Axle Steering', 'Sport Design Package']),
            ],
            [
                'make' => 'Genesis', 'model' => 'G90 3.5T e-SC', 'year' => 2024,
                'price' => 98500, 'mileage' => 4200, 'exterior_color' => 'Savile Silver',
                'interior_color' => 'Forest Green Nappa', 'body_type' => 'sedan',
                'transmission' => 'automatic', 'fuel_type' => 'hybrid', 'drivetrain' => 'awd',
                'engine' => '3.5L Twin-Turbo V6 Hybrid', 'horsepower' => 409, 'condition' => 'used',
                'featured' => false,
                'hero_image' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&q=80',
                'description' => 'Korea\'s answer to the S-Class, and it\'s shockingly good. The Ergo Motion seats with 20-way adjustment, dual-screen curved OLED display, and a level of standard equipment that makes German brands blush.',
                'features' => (['Ergo Motion Seats', 'Curved OLED Display', 'Mark Levinson 26-Speaker', 'Rear Relaxation Seat', 'Remote Parking', 'Conquer Road Noise']),
            ],
        ];

        foreach ($vehicles as $data) {
            $vin = strtoupper(substr(md5($data['make'] . $data['model'] . $data['year']), 0, 17));
            $data['vin'] = $vin;
            Vehicle::create($data);
        }
    }
}
